### ISSUE TITLE
Project Direction

### ISSUE THREAD

**Issue by saopayne** [otaruMendez/MT#1]
I think it will be good to state what you want to achieve with this project and how people can contribute. I'd love to hop in on this but I have no idea what it is to add 👍

**Comment by otaruMendez** [comment]
I am glad you are interested, I would be including a proper description with objectives in the read me soon. Cheers!

**Comment by saopayne** [comment]
Great to know 💯 . Do update this issue when the Readme has been updated.

**Comment by otaruMendez** [comment]
Hi @saopayne, I am glad to tell you that the Readme file has been updated. The Milestones file would be of great help as it tells he direction of the project and in what way you could contribute. We would be expecting your pull request soon. Cheers!
