### ISSUE TITLE
Milestone #2

### ISSUE THREAD

**Issue by saopayne** [otaruMendez/MT#5]
#### Store the diction in separate file and load that file in the main file

For the diction, is there a list available or what do you have in mind?

**Comment by otaruMendez** [comment]
I actually don't know how we can go about this, I was thinking of crowd sourcing, throwing it to the public to the populate the list. What do you think @razaqK @saopayne?

**Comment by saopayne** [comment]
Oh well, crowdsourcing is one way to go about this but with many sources come noises of different variants. We could look into getting the data ourselves, probably boring but in the short term, yes.

I suggest we build the dataset ourselves, do the compilation. Let me know your thoughts.

**Comment by otaruMendez** [comment]
I agree with you @saopayne, @razaqK?

**Comment by razaqK** [comment]
@saopayne the diction will probably be store in a document db... I agree with you on getting the data ourselves at the initial... for crowd sourcing i think we will definitely need some sort entry where data will be submitted and undergo review before moving them into the diction.

**Comment by otaruMendez** [comment]
I agree with you too @razaqK, so we would be moving the diction to a nosql DB, we would also create 2 portals, the first one would be to populate the diction and the second one would be to review the entries by the administrators. I would update the MILESTONES.md file to this effect.
